# Generated by Django 3.2.9 on 2021-11-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0003_auto_20211015_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
