# Generated by Django 3.2.9 on 2021-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0004_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='correo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
