# Generated by Django 3.2.8 on 2022-02-16 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0005_vendedor_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('descripcion_comentario', models.CharField(max_length=20)),
                ('fecha_limite', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_grupo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_comentario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('sub_grupo', models.CharField(max_length=100)),
                ('medida_mayor', models.CharField(max_length=100)),
                ('medida_menor', models.CharField(max_length=100)),
                ('precio_mayoreo', models.CharField(max_length=100)),
                ('precio_detalle', models.CharField(max_length=100)),
                ('equivalencia', models.CharField(max_length=100)),
                ('imagen', models.BinaryField(editable=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.categoria')),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.comentario')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.respuesta_comentario'),
        ),
    ]
