# Generated by Django 3.2.8 on 2022-02-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0006_auto_20220215_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nombre_actividad',
        ),
    ]
